name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: platane/snk@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
